# Generated by Django 6.0.5 on 2026-05-25 16:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP_PROCUREMENT', 'SAP Fuel & Procurement'), ('UTILITY_ELECTRICITY', 'Utility Electricity'), ('TRAVEL_CONCUR', 'Corporate Travel (Concur)')], max_length=30)),
                ('source_row_number', models.IntegerField(help_text='Row/entry index in the original file (1-based)')),
                ('raw_data', models.JSONField(help_text='Verbatim original row/entry from source file')),
                ('ghg_scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 — Direct Emissions'), ('SCOPE_2', 'Scope 2 — Purchased Energy'), ('SCOPE_3', 'Scope 3 — Other Indirect')], max_length=10)),
                ('category', models.CharField(choices=[('FUEL_COMBUSTION', 'Fuel Combustion'), ('ELECTRICITY', 'Electricity'), ('FLIGHT', 'Flight'), ('HOTEL', 'Hotel'), ('GROUND_TRANSPORT', 'Ground Transport')], max_length=30)),
                ('activity_date', models.DateField(help_text='Primary date of the activity')),
                ('period_start', models.DateField(blank=True, help_text='Start of billing/reporting period (for utility data)', null=True)),
                ('period_end', models.DateField(blank=True, help_text='End of billing/reporting period', null=True)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Quantity in original units', max_digits=16)),
                ('original_unit', models.CharField(help_text='Unit as it appeared in the source (e.g., L, TO, kWh, GAL)', max_length=20)),
                ('normalized_quantity', models.DecimalField(decimal_places=4, help_text='Quantity converted to normalized unit', max_digits=16)),
                ('normalized_unit', models.CharField(help_text='Standardized unit (e.g., liters, kg, kWh, km, room-nights)', max_length=20)),
                ('description', models.TextField(blank=True, default='', help_text='Human-readable summary of this activity')),
                ('source_metadata', models.JSONField(blank=True, default=dict, help_text='Source-specific fields: plant codes, meter IDs, flight routes, etc.')),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged for Review'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('EDITED', 'Edited'), ('STATUS_CHANGED', 'Status Changed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged')], max_length=20)),
                ('field_changed', models.CharField(blank=True, default='', max_length=100)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('changed_by', models.CharField(default='system', max_length=100)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='core.activityrecord')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='core.client'),
        ),
        migrations.CreateModel(
            name='IngestionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP_PROCUREMENT', 'SAP Fuel & Procurement'), ('UTILITY_ELECTRICITY', 'Utility Electricity'), ('TRAVEL_CONCUR', 'Corporate Travel (Concur)')], max_length=30)),
                ('file_name', models.CharField(max_length=255)),
                ('file_hash_sha256', models.CharField(blank=True, default='', help_text='SHA-256 hash for duplicate detection', max_length=64)),
                ('total_rows', models.IntegerField(default=0)),
                ('successful_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('field_mapping', models.JSONField(blank=True, default=dict, help_text='Mapping from original column names to normalized field names')),
                ('validation_errors', models.JSONField(blank=True, default=list, help_text='Per-row validation errors: [{row: int, field: str, error: str}]')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('uploaded_by', models.CharField(default='system', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_logs', to='core.client')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='ingestion_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.ingestionlog'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['client', 'source_type'], name='core_activi_client__802a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['client', 'ghg_scope'], name='core_activi_client__c10ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['client', 'review_status'], name='core_activi_client__dbc47b_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['activity_date'], name='core_activi_activit_94dfb5_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['ingestion_log'], name='core_activi_ingesti_503753_idx'),
        ),
    ]
